#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'dv-stack','console_scripts','dv_fake_sources'
__requires__ = 'dv-stack'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('dv-stack', 'console_scripts', 'dv_fake_sources')()
    )
